import {defineArrayMember, defineField, defineType} from "sanity";

export const contactPageType = defineType({
  name: "contactPage",
  title: "Contact Page",
  type: "document",
  fields: [
    defineField({
      name: "seo",
      title: "SEO",
      type: "seoMeta",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "h1",
      title: "H1",
      type: "localeString",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "introduction",
      title: "Introduction",
      type: "localeText",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "formSectionTitle",
      title: "Form Section Title",
      type: "localeString",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "formLabels",
      title: "Form Labels",
      type: "object",
      fields: [
        defineField({name: "fullName", title: "Full Name", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "agencyCompany", title: "Agency / Company Name", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "jobTitle", title: "Job Title / Role", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "email", title: "Email Address", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "phone", title: "WhatsApp or Phone", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "country", title: "Country of Origin", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "groupSize", title: "Estimated Group Size", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "travelDates", title: "Travel Dates", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "programType", title: "Program Type", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "hotelPreference", title: "Hotel Preference", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "budgetRange", title: "Budget Range", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "servicesRequired", title: "Services Required", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "specialRequirements", title: "Special Requirements", type: "localeString", validation: (rule) => rule.required()}),
        defineField({name: "referral", title: "How Did You Find Us?", type: "localeString", validation: (rule) => rule.required()}),
      ],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "programTypeOptions",
      title: "Program Type Options",
      type: "array",
      of: [defineArrayMember({type: "localeString"})],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "hotelPreferenceOptions",
      title: "Hotel Preference Options",
      type: "array",
      of: [defineArrayMember({type: "localeString"})],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "budgetRangeOptions",
      title: "Budget Range Options",
      type: "array",
      of: [defineArrayMember({type: "localeString"})],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "servicesRequiredOptions",
      title: "Services Required Options",
      type: "array",
      of: [defineArrayMember({type: "localeString"})],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "referralOptions",
      title: "Referral Options",
      type: "array",
      of: [defineArrayMember({type: "localeString"})],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "submitButtonLabel",
      title: "Submit Button Label",
      type: "localeString",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "directContactTitle",
      title: "Direct Contact Title",
      type: "localeString",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "jeannieEmail",
      title: "Jeannie Email",
      type: "string",
      validation: (rule) => rule.required().email(),
    }),
    defineField({
      name: "jeannieWhatsApp",
      title: "Jeannie WhatsApp",
      type: "localeText",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "jeannieResponseTime",
      title: "Jeannie Response Time",
      type: "localeString",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "jeannieWorkingHours",
      title: "Jeannie Working Hours",
      type: "localeString",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "jeannieLanguages",
      title: "Jeannie Languages",
      type: "localeString",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "jeannieLocation",
      title: "Jeannie Location",
      type: "localeString",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "faqSectionTitle",
      title: "FAQ Section Title",
      type: "localeString",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "faqs",
      title: "FAQs",
      type: "array",
      of: [defineArrayMember({type: "faqItem"})],
      validation: (rule) => rule.required().length(8),
    }),
  ],
  preview: {
    prepare() {
      return {title: "Contact Page"};
    },
  },
});
